name: Deploy to GitHub gh-pages branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: deploy-sites
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        commit-message: Montezuma's github action that has a lot of rocket emojis
